"""add ai interactions

Revision ID: 1b76ac017c8e
Revises: d2af3ce486b4
Create Date: 2026-09-01 09:44:27.288602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b76ac017c8e'
down_revision: Union[str, Sequence[str], None] = 'd2af3ce486b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('interaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('assistance_type', sa.String(length=50), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_index(op.f('ix_ai_interactions_assistance_type'), 'ai_interactions', ['assistance_type'], unique=False)
    op.create_index(op.f('ix_ai_interactions_correlation_id'), 'ai_interactions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_interactions_order_id'), 'ai_interactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_ai_interactions_user_id'), 'ai_interactions', ['user_id'], unique=False)
    op.alter_column('content_chunks', 'menu_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_content_chunks_cuisine'), table_name='content_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_chunks_cuisine'), 'content_chunks', ['cuisine'], unique=False)
    op.alter_column('content_chunks', 'menu_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ai_interactions_user_id'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_order_id'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_correlation_id'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_assistance_type'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
