"""add generated content

Revision ID: 61439f5238d3
Revises: 1b76ac017c8e
Create Date: 2026-09-01 11:07:16.062969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61439f5238d3'
down_revision: Union[str, Sequence[str], None] = '1b76ac017c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_content',
    sa.Column('generated_content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.menu_item_id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], ),
    sa.PrimaryKeyConstraint('generated_content_id')
    )
    op.create_index(op.f('ix_generated_content_content_type'), 'generated_content', ['content_type'], unique=False)
    op.create_index(op.f('ix_generated_content_menu_item_id'), 'generated_content', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_generated_content_restaurant_id'), 'generated_content', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_content_restaurant_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_menu_item_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_content_type'), table_name='generated_content')
    op.drop_table('generated_content')
    # ### end Alembic commands ###
