"""change failed jobs id to task id

Revision ID: a5565011bf7a
Revises: 5f23a9330c84
Create Date: 2026-08-20 12:20:57.480400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5565011bf7a'
down_revision: Union[str, Sequence[str], None] = '5f23a9330c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failed_jobs', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_failed_jobs_id'), table_name='failed_jobs')
    op.create_index(op.f('ix_failed_jobs_task_id'), 'failed_jobs', ['task_id'], unique=False)
    op.drop_column('failed_jobs', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failed_jobs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_failed_jobs_task_id'), table_name='failed_jobs')
    op.create_index(op.f('ix_failed_jobs_id'), 'failed_jobs', ['id'], unique=False)
    op.drop_column('failed_jobs', 'task_id')
    # ### end Alembic commands ###
